In [1]:
import pickle

In [2]:
import tensorflow as tf


In [3]:
keras.metrics.CategoricalAccuracy()

NameError: name 'keras' is not defined

In [ ]:
tf.Variable(A_matrix,trainable=True)

In [ ]:
keras.metrics.

In [ ]:
keras.utils.to_categorical(label_list,num_classes=80)

In [ ]:
keras.losses.BinaryCrossentropy(from_logits=true)

In [ ]:
def load_img(path):
    img=tf.io.read_file()

In [ ]:
img=tf.io.read_file(path)
img=tf.image.decode_jpeg(img,channels=3)
img=tf.image.resize(img,(448,448))

In [ ]:
img_data=tf.data.Dataset.from_tensor_slices(anno_list[:4000]['filename'])

In [ ]:
tf.nn.sigmoid_cross_entropy_with_logit

In [2]:
keras=tf.keras
tf.optimizers.SGD()

In [4]:
import pickle
result = pickle.load(open('data/coco/coco_adj.pkl', 'rb'))
result

{'nums': array([ 2243,  1171,  3924,  1618,  1804,  1884,   668,  2539,  3844,
         2287,  2241,  2098,  3734,  5968,  5028,  1340,  2791,  2080,
         8606,  1186,  2818,  3322,  8950,  3159,  3170,  1389,  6518,
         8378,  3041,  1062,  1518,  1205,  2537,  1511,  1798,   128,
         4861,  2068,   821,  1471,  1625,  3097,  2475,  1089,  2442,
         1290,  1216,  2003,   481, 45174,  2202,  3084,  1671,  2180,
         1645,   673,  1105,  3291,  2511,  2209,  1170,  2493,  2986,
         1214,  1631,  2343,  1510,  2368,  2667,   151,  2317,   700,
         2893,  2464,  4321,  3191,  2749,  2530,  1771,  1324],
       dtype=int64), 'adj': array([[  0,   0,  46, ...,   0,   0,   0],
        [  0,   0,  20, ...,  49,  45,   0],
        [ 46,  20,   0, ...,  42,  35,   1],
        ...,
        [  0,  49,  42, ...,   0, 197,   1],
        [  0,  45,  35, ..., 197,   0,   0],
        [  0,   0,   1, ...,   1,   0,   0]], dtype=int64)}

In [6]:
_adj = result['adj']
_nums = result['nums']

In [13]:
_adj.shape

(80, 80)

In [7]:
import numpy as np
np.unique(_nums)#有八十的大种类

array([  128,   151,   481,   668,   673,   700,   821,  1062,  1089,
        1105,  1170,  1171,  1186,  1205,  1214,  1216,  1290,  1324,
        1340,  1389,  1471,  1510,  1511,  1518,  1618,  1625,  1631,
        1645,  1671,  1771,  1798,  1804,  1884,  2003,  2068,  2080,
        2098,  2180,  2202,  2209,  2241,  2243,  2287,  2317,  2343,
        2368,  2442,  2464,  2475,  2493,  2511,  2530,  2537,  2539,
        2667,  2749,  2791,  2818,  2893,  2986,  3041,  3084,  3097,
        3159,  3170,  3191,  3291,  3322,  3734,  3844,  3924,  4321,
        4861,  5028,  5968,  6518,  8378,  8606,  8950, 45174],
      dtype=int64)

In [8]:
_nums.shape

(80,)

In [10]:
import numpy as np
_nums = _nums[:, np.newaxis]
_adj = _adj / _nums

In [11]:
_nums.shape

(80, 1)

In [11]:
_adj

array([[0.        , 0.        , 0.02050825, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01707942, ..., 0.04184458, 0.03842869,
        0.        ],
       [0.01172273, 0.00509684, 0.        , ..., 0.01070336, 0.00891947,
        0.00025484],
       ...,
       [0.        , 0.01936759, 0.01660079, ..., 0.        , 0.07786561,
        0.00039526],
       [0.        , 0.02540937, 0.01976285, ..., 0.11123659, 0.        ,
        0.        ],
       [0.        , 0.        , 0.00075529, ..., 0.00075529, 0.        ,
        0.        ]])

In [16]:
t=0.4#这里对应论文中的二值化
_adj[_adj < t] = 0
_adj[_adj >= t] = 1


In [18]:
np.unique(_adj)

array([0., 1.])

In [24]:
a2=_adj.sum(0, keepdims=True)
a2+=1e-6
0.25/a2

array([[2.50000000e+05, 2.50000000e+05, 2.50000000e+05, 2.50000000e+05,
        2.49999750e-01, 2.49999750e-01, 2.50000000e+05, 2.50000000e+05,
        2.50000000e+05, 2.50000000e+05, 2.50000000e+05, 2.50000000e+05,
        2.50000000e+05, 8.33333056e-02, 1.24999938e-01, 2.50000000e+05,
        2.50000000e+05, 2.50000000e+05, 4.16666597e-02, 2.50000000e+05,
        2.50000000e+05, 2.50000000e+05, 8.33333056e-02, 2.50000000e+05,
        2.49999750e-01, 2.50000000e+05, 4.99999900e-02, 2.27272707e-02,
        2.50000000e+05, 2.50000000e+05, 2.50000000e+05, 2.50000000e+05,
        2.49999750e-01, 2.50000000e+05, 2.50000000e+05, 2.50000000e+05,
        2.50000000e+05, 2.50000000e+05, 2.50000000e+05, 2.49999750e-01,
        2.50000000e+05, 2.49999750e-01, 1.24999938e-01, 2.49999750e-01,
        2.50000000e+05, 2.49999750e-01, 2.49999750e-01, 8.33333056e-02,
        2.50000000e+05, 4.54545446e-03, 2.50000000e+05, 2.50000000e+05,
        2.49999750e-01, 2.50000000e+05, 2.50000000e+05, 2.500000

In [28]:
_adj = _adj * 0.25 / (_adj.sum(0, keepdims=True) + 1e-6)
_adj = _adj + np.identity(80, np.int)


In [40]:
_adj.shape

(80, 80)

In [38]:
D=_adj.sum(1)**-0.5
D

array([1.        , 0.89442755, 0.997735  , 0.997735  , 0.89280574,
       0.85139723, 1.        , 1.        , 0.997735  , 0.997735  ,
       1.        , 0.997735  , 0.997735  , 0.997735  , 0.98663642,
       1.        , 0.97766522, 0.98663642, 0.997735  , 0.93342786,
       1.        , 0.997735  , 0.98663642, 0.997735  , 0.9587598 ,
       1.        , 0.98663642, 0.9587598 , 0.997735  , 0.997735  ,
       0.997735  , 0.97766522, 0.86800081, 0.997735  , 1.        ,
       0.97766522, 0.997735  , 0.997735  , 0.997735  , 0.81649713,
       0.997735  , 0.86800081, 0.997735  , 0.85280333, 0.997735  ,
       0.81649713, 1.        , 0.97979598, 0.97766522, 1.        ,
       0.98663642, 0.997735  , 0.92582036, 0.89280574, 0.96346786,
       1.        , 1.        , 1.        , 0.997735  , 0.997735  ,
       0.997735  , 0.912008  , 0.89280574, 0.97979598, 0.997735  ,
       0.997735  , 0.997735  , 0.94091035, 0.997735  , 0.82807919,
       0.97979598, 0.97766522, 0.97766522, 0.997735  , 0.97766

In [41]:

D=np.diag(D)
D

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.89442755, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.997735  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.92823449,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [42]:
res=D*_adj*D
res

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.80000064, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.99547513, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.86161928,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [43]:
res.shape

(80, 80)

In [ ]:
coco_glove_word2vec.pkl

In [45]:
word2vec= pickle.load(open('data/coco/coco_glove_word2vec.pkl', 'rb'))
word2vec.shape

(80, 300)

In [46]:
import spektral as sp

In [50]:
x1=([word2vec,res])
x2=sp.layers.GCNConv(1024)(x1)
x2=tf.nn.leaky_relu(x2)
x3=sp.layers.GCNConv(2048)([x2,res])
x3=tf.nn.leaky_relu(x3)
x3.shape

TensorShape([80, 2048])

In [47]:
import tensorflow as tf
keras=tf.keras

In [ ]:
keras.activations.

In [ ]:
tf.nn.leaky_relu()

In [51]:
x3

<tf.Tensor: shape=(80, 2048), dtype=float32, numpy=
array([[-0.0271035 , -0.00437585,  0.25817418, ...,  0.01895901,
         0.05246466,  0.02786351],
       [-0.01316893,  0.04437647, -0.00094192, ..., -0.00048493,
        -0.03359246,  0.0476577 ],
       [-0.04703877,  0.18418726,  0.17084609, ...,  0.18073298,
        -0.01514583,  0.05934539],
       ...,
       [ 0.1524185 ,  0.16376716, -0.05891035, ..., -0.03537911,
         0.00284483, -0.0396538 ],
       [ 0.08000706,  0.05392345,  0.05588702, ..., -0.02053322,
        -0.00617781, -0.00354422],
       [ 0.0658873 ,  0.09739785,  0.01034234, ..., -0.0429404 ,
        -0.01856428, -0.02232479]], dtype=float32)>

In [52]:
resnet=keras.applications.ResNet101(include_top=False,weights='imagenet',input_shape=(448,448,3))
resnet.summary()

171450368/171446536 [==============================] - 21s 0us/step
Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 448, 448, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 454, 454, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 224, 224, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 224, 224, 64) 256         conv1_conv[0][0]                 
______________________

In [73]:
inputs1=keras.Input(shape=(448,448,3))

In [74]:
output=resnet(inputs1)

In [75]:
output

<KerasTensor: shape=(None, 14, 14, 2048) dtype=float32 (created by layer 'resnet101')>

In [76]:
output=keras.layers.MaxPool2D(14,14)(output)
output

<KerasTensor: shape=(None, 1, 1, 2048) dtype=float32 (created by layer 'max_pooling2d_1')>

In [77]:
output=tf.reshape(output,(-1,output.shape[-1]))
output

<KerasTensor: shape=(None, 2048) dtype=float32 (created by layer 'tf.reshape_2')>

In [78]:
x3.shape

(2048, 80)

In [80]:
x3=tf.experimental.numpy.moveaxis(x3,0,1)
x3.shape

(2048, 80)

In [81]:
x = tf.matmul(output, x3)


In [82]:
x.shape

TensorShape([None, 80])

In [83]:
model=keras.models.Model(inputs=inputs1,outputs=x)

In [84]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 448, 448, 3)]     0         
_________________________________________________________________
resnet101 (Functional)       (None, 14, 14, 2048)      42658176  
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 1, 1, 2048)        0         
_________________________________________________________________
tf.reshape_2 (TFOpLambda)    (None, 2048)              0         
_________________________________________________________________
tf.linalg.matmul_1 (TFOpLamb (None, 80)                0         
Total params: 42,658,176
Trainable params: 42,552,832
Non-trainable params: 105,344
_________________________________________________________________


In [85]:
model(inputs1)

<KerasTensor: shape=(None, 80) dtype=float32 (created by layer 'model_1')>

In [104]:
class MLGCN(keras.Model):
    def __init__(self,A_matrix):
        super(MLGCN,self).__init__()
        self.gcn1=sp.layers.GCNConv(1024)
        self.gcn2=sp.layers.GCNConv(2048)
        self.A_matrix=A_matrix
        self.maxpool=keras.layers.GlobalMaxPool2D()
    def call(self,input,word2vec):
        gcnoutput=self.gcn1([word2vec,self.A_matrix])
        gcnoutput=tf.nn.leaky_relu(gcnoutput)
        gcnoutput=self.gcn2([gcnoutput,self.A_matrix])
        gcnoutput=tf.nn.leaky_relu(gcnoutput)
        gcnoutput=tf.experimental.numpy.moveaxis(gcnoutput,0,1)
        feature_output=resnet(input)
        feature_output=self.maxpool(feature_output)
        output=tf.matmul(feature_output,gcnoutput)
        return output







In [ ]:
keras.losses.BinaryCrossentropy(from_logits=True)

In [97]:
keras.layers.GlobalMaxPool2D()

In [105]:
m1=MLGCN(res)

In [106]:
input=keras.Input(shape=(448,448,3))


In [107]:
m1(input,word2vec)

<KerasTensor: shape=(None, 80) dtype=float32 (created by layer 'mlgcn_4')>

In [ ]:
keras.metrics.BinaryAccuracy()